spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9095
management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Api Gateway"
    description: "This is Api Gateway for common entry Point"
    version: "1.0V"

resilience4j:
  circuitBreaker:
    configs:
      default:
        sliding-window-size:
          permitted-number-of-calls-in-half-open-state: 2
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10000

