spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      httpclient:
        response-timeout: 5s
        connect-timeout: 1000

      routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - StripPrefix=1
  data:
    redis:
      host:
        port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://127.0.0.1:8080/realms/classic-cravings/protocol/openid-connect/certs"
#        username: guest
#        password: guest


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9095
management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Api Gateway"
    description: "This is Api Gateway for common entry Point"
    version: "1.0V"

resilience4j:
  circuitBreaker:
    configs:
      default:
        sliding-window-size:
          permitted-number-of-calls-in-half-open-state: 2
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10000

