spring:
  application:
    name: "FOOD-SERVICE"
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:9096/"

# eureka configuration

  rabbitMQ:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    openFeign:
      circuit-breaker:
        enabled: true


resilience4j:
  circuitBreaker:
    configs:
      default:
        sliding-window-size:
          permitted-number-of-calls-in-half-open-state: 2
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10000
